version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serendib"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-taubv5edqbxf"
s3_prefix = "serendib"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
